### PR TITLE
Fix time zone issues, optimize date for db query

### PR DESCRIPTION
**Pull request by laomo**
fix https://github.com/antoniolg/Kotlin-for-Android-Developers/issues/6

### CODE REVIEW

**Comment by antoniolg** [comment]
Thanks for this! Give me some time to try it and I'll merge.

**Comment by antoniolg** [comment]
I'm redoing this repo with some book updates, so I won't be able to merge this PR.  But I'll add your fix, so what I've thought is that I'm going to add a collaborators section in the readme.

I can't do it anything else, because people who get the book need the right fixes at the right commit. An extra commit at the head of the branch won't help. So I need to `push -f` this branch.

Thanks again for finding a solution!

**Comment by antoniolg** [comment]
Tried this, but it wasn't working either. The dates this API return are rather random for some strange reason. The approach I took in the end is the same I saw other people use with this API: as I know that the first forecast I receive is for today, I iterate and generate the dates manually.

This will land master in the following day, but you can already [see it here](https://github.com/antoniolg/Kotlin-for-Android-Developers/blob/chapter-10/app/src/main/java/com/antonioleiva/weatherapp/domain/mappers/ForecastDataMapper.kt#L18).

I'm closing this PR in favour of the other solution. Thanks for your help!

**Comment by laomo** [comment]
get it.

**Pull request closed without merging**
